language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - cmake-data
    - gcc-4.9
    - g++-4.9
    - libglew-dev
    - libglm-dev
    - freeglut3-dev
    - libgtest-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
  - cmake .
  - make -j4
  - ctest --output-on-failure
